# Generated by Django 4.2.1 on 2023-09-21 19:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=7)),
                ('tag', models.CharField(max_length=24)),
                ('content', models.CharField(default='[]', max_length=500)),
                ('url', models.CharField(default='', max_length=30)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2023, 9, 21, 21, 56, 13, 926329))),
                ('public_list', models.CharField(default='False', max_length=20)),
                ('public_list_passwd', models.CharField(default='', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkListProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(default='[]', max_length=500)),
                ('foreign_lists', models.CharField(default='[]', max_length=500)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_list_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
