# Generated by Django 4.2.1 on 2023-09-21 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_list_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 21, 56, 59, 754607)),
        ),
    ]
