# Generated by Django 4.2.1 on 2023-09-24 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_list_api', '0008_alter_list_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 13, 7, 34, 773170)),
        ),
    ]
