# Generated by Django 4.2.5 on 2023-10-04 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_list_api', '0012_alter_list_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 21, 2, 54, 385774)),
        ),
    ]
