# Generated by Django 4.2 on 2023-04-20 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 7, 10, 46, 844127, tzinfo=datetime.timezone.utc)),
        ),
    ]
