# Generated by Django 4.2.1 on 2023-06-28 13:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppWideData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_baner', models.CharField(default='', max_length=500)),
                ('invatation_codes', models.CharField(default='[]', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(default='[]', max_length=500)),
                ('last_login', models.DateTimeField(default=datetime.datetime(2023, 6, 28, 15, 57, 20, 17801))),
                ('foreign_lists', models.CharField(default='[]', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=7)),
                ('tag', models.CharField(max_length=24)),
                ('content', models.CharField(default='[]', max_length=500)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2023, 6, 28, 15, 57, 20, 18146))),
                ('public_list', models.CharField(default='False', max_length=20)),
                ('public_list_passwd', models.CharField(default='', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
