# Generated by Django 4.2 on 2023-05-16 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 18, 41, 59, 691641)),
        ),
    ]
