# Generated by Django 4.2.1 on 2023-06-28 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 15, 57, 22, 586521)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 15, 57, 22, 586198)),
        ),
    ]
