# Generated by Django 4.2 on 2023-05-16 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 19, 6, 20, 315886)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
