# Generated by Django 4.2.1 on 2023-06-28 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_list_creation_date_alter_profile_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='url',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='list',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 18, 16, 17, 437292)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 18, 16, 17, 436932)),
        ),
    ]
