# Generated by Django 4.2.1 on 2023-06-28 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_list_url_alter_list_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 18, 16, 20, 220)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 18, 16, 19, 999885)),
        ),
    ]
