# Generated by Django 4.2 on 2023-05-21 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='content',
            field=models.CharField(default='[]', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 19, 51, 45, 276158)),
        ),
    ]
