# Generated by Django 4.2 on 2023-06-17 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppWideData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_baner', models.CharField(default='', max_length=500)),
                ('invatation_codes', models.CharField(default='[]', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 17, 22, 9, 35, 293616)),
        ),
    ]
