# Generated by Django 4.2 on 2023-06-29 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_list_creation_date_alter_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 12, 13, 14, 915093)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 12, 13, 14, 914090)),
        ),
    ]
