# Generated by Django 4.2.1 on 2023-09-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppWideData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_baner', models.CharField(default='', max_length=500)),
                ('invatation_codes', models.CharField(default='[]', max_length=200)),
            ],
        ),
    ]
