# Generated by Django 4.2.1 on 2023-09-23 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0, max_length=10)),
                ('lon', models.FloatField(default=0, max_length=10)),
                ('date', models.TextField(max_length=8)),
                ('current_weather', models.TextField(max_length=1000)),
                ('minutes', models.TextField(blank=True, max_length=1000, null=True)),
                ('minutly_weather', models.TextField(blank=True, max_length=1000, null=True)),
                ('days', models.TextField(blank=True, max_length=1000, null=True)),
                ('dayly_weather', models.TextField(blank=True, max_length=1000, null=True)),
                ('alert', models.TextField(blank=True, max_length=1000, null=True)),
                ('historical', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('custom_coordinates', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('default_location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_api_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
