# Generated by Django 4.2.1 on 2023-09-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='dayly_weather',
            new_name='forecast_time',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='days',
            new_name='forecast_weather',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='minutly_weather',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='time',
            field=models.TextField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherprofile',
            name='default_location',
            field=models.CharField(default='Hamburg', max_length=100),
        ),
    ]
