# Generated by Django 4.2.1 on 2023-09-23 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_rename_dayly_weather_weatherdata_forecast_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='forecast_time',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='forecast_weather',
        ),
        migrations.CreateModel(
            name='ForecastWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0, max_length=10)),
                ('lon', models.FloatField(default=0, max_length=10)),
                ('date', models.TextField(max_length=8)),
                ('time', models.TextField(max_length=4)),
                ('forecast_weather', models.TextField(max_length=1000)),
                ('associated_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_weather', to='weather_api.weatherdata')),
            ],
        ),
    ]
