# Generated by Django 4.2.1 on 2023-09-23 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0004_remove_forecastweatherdata_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastweatherdata',
            name='associated_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.weatherdata'),
        ),
    ]
