# Generated by Django 4.2.1 on 2023-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0005_alter_forecastweatherdata_associated_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastweatherdata',
            name='date',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='forecastweatherdata',
            name='time',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='date',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='time',
            field=models.IntegerField(max_length=4),
        ),
    ]
