# Generated by Django 4.2.5 on 2023-10-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0007_forecastweatherdata_source_weatherdata_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherprofile',
            name='custom_coordinates',
            field=models.CharField(blank=True, default='{}', max_length=100, null=True),
        ),
    ]
